In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1 = np.zeros([2,2])
arr1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [5]:
arr2 = np.ones([1,2])
arr2

array([[ 1.,  1.]])

In [6]:
arr3 = np.full([1,2],10)
arr3

array([[10, 10]])

In [7]:
arr4 = np.eye(3)
arr4

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
arr5 = np.random.random([2,2])
arr5

array([[ 0.7720862 ,  0.48399712],
       [ 0.9595224 ,  0.30506971]])

In [9]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3.ndim)

1
2
3


In [10]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [11]:
print(arr1[0])
print(arr2[1])
print(arr3[0][1])

1
[4 5 6]
[4 5 6]


In [12]:
print(arr3[0,0,1])
print(arr3[0][0][1])

2
2


In [13]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr5 = arr4[:2, :]
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr1 = np.array([[1,2],[3,4],[5,6]])
idx = (arr1 > 3)
idx

array([[False, False],
       [False,  True],
       [ True,  True]], dtype=bool)

In [15]:
arr1[idx]

array([4, 5, 6])

In [16]:
arr1 = np.array([1])
arr1.dtype

dtype('int32')

In [17]:
arr2 = np.array([1,0])
arr2.dtype

dtype('int32')

In [18]:
arr3 = np.array([1,2], dtype = np.float64)
arr3.dtype

dtype('float64')

In [19]:
arr1 = np.array([[1,2],[3,4]], dtype = np.float64)
arr2 = np.array([[5,6],[7,8]], dtype = np.float64)
print(arr1)
print()
print(arr2)

[[ 1.  2.]
 [ 3.  4.]]

[[ 5.  6.]
 [ 7.  8.]]


In [20]:
arr1 + arr2

array([[  6.,   8.],
       [ 10.,  12.]])

In [21]:
arr1 - arr2

array([[-4., -4.],
       [-4., -4.]])

In [22]:
arr1 * arr2 #행렬의 곱연산이 아니다!!!!!

array([[  5.,  12.],
       [ 21.,  32.]])

In [23]:
arr1 / arr2

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [24]:
np.sqrt(arr1)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [25]:
# 벡터의 내적
vector1 = np.array([1,2])
vector2 = np.array([3,4])

print(vector1)
print(vector2)
print('1*3   +   2*4  =  3 + 8  =  11')
print('벡터의 내적 np.dot ----> ',np.dot(vector1, vector2))

[1 2]
[3 4]
1*3   +   2*4  =  3 + 8  =  11
벡터의 내적 np.dot ---->  11


In [26]:
# 행렬의 곱연산
arr1 = np.array([[1,2],[3,4]], dtype = np.float64)
arr2 = np.array([[5,6],[7,8]], dtype = np.float64)

print(arr1)
print(arr2)
print("우리가 알고 있는 그 행렬의 곱을 하면 된다.")
print('행렬의 곱연산 np.dot ---->', '\n',np.dot(arr1, arr2))

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]
우리가 알고 있는 그 행렬의 곱을 하면 된다.
행렬의 곱연산 np.dot ----> 
 [[ 19.  22.]
 [ 43.  50.]]


In [27]:
arr1 = np.array([[1,2],[3,4]], dtype = np.float64)
arr1

array([[ 1.,  2.],
       [ 3.,  4.]])

In [28]:
np.sum(arr1)

10.0

In [29]:
np.sum(arr1, axis = 0)

array([ 4.,  6.])

In [30]:
np.sum(arr1, axis = 1)

array([ 3.,  7.])

In [31]:
arr1 = np.array([[1,2],[3,4]], dtype = np.float64)
arr1

array([[ 1.,  2.],
       [ 3.,  4.]])

In [32]:
arr1.T # 행과 열을 바꿈

array([[ 1.,  3.],
       [ 2.,  4.]])

### 데이터 불러오기 (수치형 데이터 불러오기)
##### loadtxt() 함수를 이용해 수치형 데이터(정수 혹은 실수형)를 불러올 수 있다.

In [33]:
data = np.loadtxt('test-data.csv', delimiter = ',')

In [34]:
data

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  53.,   46.,   55.,  101.],
       [  69.,   74.,   77.,  149.],
       [  47.,   56.,   60.,  115.],
       [  87.,   79.,   90.,  175.],
       [  79.,   70.,   88.,  164.],
       [  69.,   70.,   73.,  141.],
       [  70.,   65.,   74.,  141.],
       [  93.,   95.,   91.,  184.],
       [  79.,   80.,   73.,  152.],
       [  70.,   73.,   78.,  148.],
       [  93.,   89.,   96.,  192.],
       [  78.,   75.,   68.,  147.],
       [  81.,   90.,   93.,  183.],
       [  88.,   92.,   86.,  177.],
       [  78.,   83.,   77.,  159.],
       [  82.,   86.,   90.,  177.],
       [  86.,   82.,   89.,  175.],
       [  78.,   83.,   85.,  175.],
       [  76.,   83.,   71.,  149.],
       [  96.,   93.,   95.,  192.]])

In [35]:
data = np.genfromtxt('building.csv', dtype = None, delimiter = ',')

The |S1 and |S2 strings are data type descriptors; the first means the array holds strings of length 1, the second of length 2. The | pipe symbol is the byteorder flag; in this case there is no byte order flag needed, so it's set to |, meaning not applicable.<br><br>
Data type of the resulting array. If <b>None</b>, the dtypes will be determined by the contents of each column, individually. <br><br>
<b>replace_space</b> : char, optional
Character(s) used in replacement of white spaces in the variables names. By default, use a ‘__’.

In [36]:
data

array([[b'building', b'city', b'height'],
       [b'Empire State Building', b'New York', b'381'],
       [b'Eiffel Tower', b'Paris', b'300'],
       [b'63 building', b'Seoul', b'250']],
      dtype='|S21')

## 실습 2-1. 랜덤 벡터 생성과 정렬
#### ** 길이 10인 랜덤 벡터(1차원 배열)을 생성하고 이를 정렬한다.

- 오름차순과 내림차순으로 한 번 씩 정렬해 본다.

In [37]:
arr_original = np.random.random(size=10)
arr_original

array([ 0.2809079 ,  0.34932424,  0.30084801,  0.65102335,  0.47506618,
        0.14544918,  0.04832645,  0.34280312,  0.07981576,  0.1238972 ])

In [38]:
np.sort(arr_original) #오름차순 정렬

array([ 0.04832645,  0.07981576,  0.1238972 ,  0.14544918,  0.2809079 ,
        0.30084801,  0.34280312,  0.34932424,  0.47506618,  0.65102335])

In [39]:
#내림차순 정렬
print(type(np.sort(arr_original)[::-1]))
print(type(np.array(sorted(arr_original, reverse = True))))
print(type(sorted(arr_original, reverse = True)))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>


## 실습 2-2. 벡터를 행렬로 변환하기
#### ** 길이 9의 벡터(1차원 배열)를 생성하고 이를 3X3 크기의 행렬로 변환한다.
- Numpy의 arange()함수를 이용해 0부터 8까지의 정수를 담은 1차원 배열을 생성한다.
- 이를 reshape() 함수로 2차원 배열로 변환한다.

In [40]:
arr_original = np.arange(9)
arr_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr_original.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 실습 2-3. 대각행렬(diagonal matrix)
#### ** 실습 2-2에서 생성한 행렬을 대각행렬로 변환해 본다.
- 우선 행렬의 주대각 원소(대각선상에 있는 원소)만 1차원 배열로 출력해 본다.
- 3x3 대각행렬(정사각행렬의 주대각 성분 이외의 모든 성분이 0인 행렬)로 변환해본다.

In [42]:
arr_reshaped = arr_original.reshape(3,3)

In [47]:
diag = np.sum(arr_reshaped * np.eye(3), axis = 1)
diag

array([ 0.,  4.,  8.])

In [48]:
diag_mat = arr_reshaped * np.eye(3)
diag_mat

array([[ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  8.]])

## 실습 2-4. 행렬 정규화(normalization)
#### ** 정수로 이루어진 5x5 행렬을 만들고 이를 정규화해본다.
- randint() 함수를 이용해 1부터 100사이의 정수로 이루어진 행렬을 생성한다.
- 행렬 내의 값들을 정규화 한다.
- X' = (X - Xmin) / (Xmax - Xmin)

In [64]:
arr_original = np.array(np.random.randint(1,100,25))
arr_original

array([96, 70, 53, 85, 12, 81, 43, 75, 73, 85, 62, 12, 14, 34, 64, 35, 89,
       61, 10, 95, 62, 57, 92, 14, 89])

In [67]:
arr = arr_original.reshape(5,5)
arr

array([[96, 70, 53, 85, 12],
       [81, 43, 75, 73, 85],
       [62, 12, 14, 34, 64],
       [35, 89, 61, 10, 95],
       [62, 57, 92, 14, 89]])

In [68]:
def normalizer(x):
    Xmin = np.min(x)
    Xmax = np.max(x)
    return (x - Xmin)/(Xmax - Xmin)

arr_normalized = normalizer(arr)

arr_normalized

array([[ 1.        ,  0.69767442,  0.5       ,  0.87209302,  0.02325581],
       [ 0.8255814 ,  0.38372093,  0.75581395,  0.73255814,  0.87209302],
       [ 0.60465116,  0.02325581,  0.04651163,  0.27906977,  0.62790698],
       [ 0.29069767,  0.91860465,  0.59302326,  0.        ,  0.98837209],
       [ 0.60465116,  0.54651163,  0.95348837,  0.04651163,  0.91860465]])

## 실습 2-5. 행렬 곱(matrix multiplication)
- 아래의 행렬 곱 연산을 수행한다.
- np.dot() 함수를 활용한다.

In [69]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

In [70]:
result = np.dot(A,B)
result

array([[22, 28],
       [49, 64]])

## 실습 2-6. 주식 데이터 불러오기
#### ** stock-data.csv의 데이터를 불러온다.
- 1열부터 4열 ('Open', 'High', 'Low', 'Volume')까지의 데이터는 x_data로 저장하고 5열 ('Close')의 데이터는 y_data로 저장한다.
- 즉, x_data의 shape은 (732,4), y_data의 shape은 (732,) 혹은 (732,1)이 되어야 한다.

In [90]:
# 7번이랑 똑같으니까 ㅎ.ㅎ

## 실습 2-7. 당뇨 데이터 불러오기
#### ** diabetes-data.csv의 데이터를 불러온다.
- 1열부터 8열까지의 데이터는 x_data로 저장하고 9열의 데이터는 y_data로 저장한다.
- 즉, x_data의 shape은 (759, 8), y_data의 shape(759,) 혹은 (759,1)이 되어야 한다.

In [75]:
data = np.genfromtxt('diabetes-data.csv', dtype = float, delimiter = ',')

In [77]:
data.shape

(759, 9)

In [84]:
x_data = data[:,:8]
y_data = data[:,-1]

In [85]:
print(x_data.shape)
print(y_data.shape)

(759, 8)
(759,)


In [89]:
x_data[0:10]

array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0.        ,
         0.052161  , -0.952178  , -0.733333  ],
       [-0.764706  ,  0.979899  

In [88]:
y_data[0:10]

array([ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.])